### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by vuki656**
- Added field for the stack trace
- Made repro, expected and actual fields required
- Added link to discussions

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
Thank you for this! The only small thing I would change is the description of the debug log, since it's more about reporting on what the plugin is doing internally (unhandled exceptions should show a proper error stack trace). I think we can make the same change to the null-ls debug description too.

**Comment by vuki656** [comment]
Sure thing. 

What did you have in mind?

**Comment by jose-elias-alvarez** [comment]
I think something simple and non-specific like "Debug output from `:messages`" would work.

**Comment by vuki656** [comment]
Done, feel free to merge.

**Comment by jose-elias-alvarez** [comment]
Thank you so much! I was thinking about running `stylua` automatically too, since not everybody runs it and I don't want to create a lot of useless commits (which is something I've seen in a lot on other plugins recently). That would be a huge help too.

**Comment by vuki656** [comment]
> Thank you so much! I was thinking about running `stylua` automatically too, since not everybody runs it and I don't want to create a lot of useless commits (which is something I've seen in a lot on other plugins recently). That would be a huge help too.

Wait, not sure I follow, would you like to have stylua run on PRs or? 

True that that would result in extra commits just for code style but those can either be squashed or if you have diagnostics on, handled right in the editor.

**Comment by jose-elias-alvarez** [comment]
In short: yes, let's set it up, if it's not too much trouble.

**Pull request merged**
